#!/usr/bin/env node
/**
 * Rebuild screenshots/archive/INDEX.md from the on-disk archive entries.
 *
 * Each entry under screenshots/archive/ that contains a meta.json becomes a
 * row in the index, reverse-chronological. The desktop screenshot (when
 * present) is embedded as the thumbnail. INDEX.md is overwritten on every
 * run — don't edit it by hand.
 */

import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const ARCHIVE = join(ROOT, 'screenshots', 'archive');
const INDEX = join(ARCHIVE, 'INDEX.md');

if (!existsSync(ARCHIVE)) {
  writeFileSync(INDEX, '# Design archive\n\n_No entries yet — run `pnpm snap <slug> "<summary>"`._\n');
  console.log('snap:index: archive empty, wrote placeholder INDEX.md');
  process.exit(0);
}

const entries = readdirSync(ARCHIVE, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => {
    const path = join(ARCHIVE, d.name);
    const metaPath = join(path, 'meta.json');
    if (!existsSync(metaPath)) return null;
    let meta;
    try { meta = JSON.parse(readFileSync(metaPath, 'utf8')); }
    catch { return null; }
    return { folder: d.name, path, meta };
  })
  .filter(Boolean)
  .sort((a, b) => (b.meta.captured_at || '').localeCompare(a.meta.captured_at || ''));

const lines = [
  '# Design archive',
  '',
  '_Reverse-chronological history of significant design moments. Generated by `scripts/update-index.mjs`. Run `pnpm snap <slug> "<summary>"` to add an entry._',
  '',
  `**${entries.length}** ${entries.length === 1 ? 'entry' : 'entries'}.`,
  '',
];

for (const e of entries) {
  const m = e.meta;
  const thumb = (m.captures || []).find((c) => c.viewport?.startsWith('desktop'))
              || (m.captures || [])[0];
  const thumbRel = thumb ? `${e.folder}/${thumb.file}` : null;
  lines.push(`## ${m.date} — ${m.slug}`);
  lines.push('');
  if (m.summary) lines.push(`> ${m.summary}`);
  lines.push('');
  if (thumbRel) {
    lines.push(`[![${m.slug}](./${thumbRel})](./${e.folder}/)`);
    lines.push('');
  }
  const meta = [];
  if (m.git?.branch) meta.push(`branch: \`${m.git.branch}\``);
  if (m.git?.commit) meta.push(`commit: \`${m.git.commit}\``);
  if (m.captured_at) meta.push(`captured: \`${m.captured_at}\``);
  if (meta.length) lines.push(meta.join(' · '));
  lines.push('');
  if (m.captures?.length) {
    lines.push('Captures: ' + m.captures.map((c) =>
      `[${c.viewport}](./${e.folder}/${c.file})`).join(' · '));
    lines.push('');
  }
  lines.push('---');
  lines.push('');
}

writeFileSync(INDEX, lines.join('\n'));
console.log(`snap:index: wrote ${INDEX} (${entries.length} entries)`);
